### PR TITLE
Enabled multiple java version 11, 15, 17 compatibility build

### PR DESCRIPTION
**Pull request by hamid646m**

### CODE REVIEW

**Review by badgerwithagun — DISMISSED** [review]

**Comment by hamid646m** [comment]
it should have failed for 17 and windows as i was not sure if the condition i added would work for docker. i included docker for windows too. now, the only thing that should fail is java 17 ( for all OS until the other PR is merged)

**Comment by badgerwithagun** [comment]
@hamid646m looks like we're still getting failures.

**Comment by hamid646m** [comment]
@badgerwithagun  it was missing my changes from other branch. So ubuntu-17 should definitely pass, not sure about others, i will take a look

**Comment by hamid646m** [comment]
so docker is not install by default on windows and mac os and it doesn't seem easy to install ones. i will remove it for now.

**Pull request merged**
