### PR TITLE
Feature : Oracle integration

### PR DESCRIPTION
**Pull request by RomainWilbert**
Implemented with Oracle-XE (gvenzl/oracle-xe:18-slim).

### CODE REVIEW

**Comment by RomainWilbert** [comment]
Hi @badgerwithagun !

I have trouble to make the acceptance test with Oracle working. When i launch my tests inside IDE it's fine, when i make a Maven build, test is stuck in an inifite loop

`09:42:59.523 [pool-57-thread-1] INFO  SESSION-KEY= c.g.t.TransactionOutboxImpl - Processed BEEF.process(3, "Whee") [062070a9-8a5b-4202-9d68-dda74e9e91c5]
09:42:59.523 [main] INFO  SESSION-KEY= c.g.t.a.AbstractAcceptanceTest - The entry life cycle is: [TransactionOutboxEntry(id=062070a9-8a5b-4202-9d68-dda74e9e91c5, uniqueRequestId=null, invocation=Invocation(className=BEEF, methodName=process, parameterTypes=[int, class java.lang.String], args=[3, Whee], mdc=null), lastAttemptTime=null, nextAttemptTime=2022-10-10T07:42:58.638Z, attempts=0, blocked=false, processed=false, version=0), TransactionOutboxEntry(id=062070a9-8a5b-4202-9d68-dda74e9e91c5, uniqueRequestId=null, invocation=Invocation(className=BEEF, methodName=process, parameterTypes=[int, class java.lang.String], args=[3, Whee], mdc=null), lastAttemptTime=2022-10-10T07:42:58.176477Z, nextAttemptTime=2022-10-10T07:42:58.676Z, attempts=1, blocked=false, processed=false, version=1), TransactionOutboxEntry(id=062070a9-8a5b-4202-9d68-dda74e9e91c5, uniqueRequestId=null, invocation=Invocation(className=BEEF, methodName=process, parameterTypes=[int, class java.lang.String], args=[3, Whee], mdc=null), lastAttemptTime=2022-10-10T07:42:58.823381Z, nextAttemptTime=2022-10-10T07:42:59.323Z, attempts=2, blocked=true, processed=false, version=3), TransactionOutboxEntry(id=062070a9-8a5b-4202-9d68-dda74e9e91c5, uniqueRequestId=null, invocation=Invocation(className=BEEF, methodName=process, parameterTypes=[int, class java.lang.String], args=[3, Whee], mdc=null), lastAttemptTime=2022-10-10T07:42:59.477174Z, nextAttemptTime=2022-10-10T07:42:59.977Z, attempts=0, blocked=false, processed=false, version=4)]
09:42:59.525 [Thread-275] ERROR SESSION-KEY= c.g.t.a.AbstractAcceptanceTest - Error flushing transaction outbox. Pausing
java.util.NoSuchElementException: null
	at java.base/java.util.LinkedList.removeFirst(LinkedList.java:274)
	at java.base/java.util.LinkedList.pop(LinkedList.java:805)
	at com.gruelbox.transactionoutbox.AbstractThreadLocalTransactionManager.popTransaction(AbstractThreadLocalTransactionManager.java:52)
	at com.gruelbox.transactionoutbox.SimpleTransactionManager.withTransaction(SimpleTransactionManager.java:71)
	at com.gruelbox.transactionoutbox.SimpleTransactionManager.inTransactionReturnsThrows(SimpleTransactionManager.java:22)
	at com.gruelbox.transactionoutbox.TransactionManager.lambda$inTransactionReturns$2(TransactionManager.java:94)
	at com.gruelbox.transactionoutbox.Utils.uncheckedly(Utils.java:48)
	at com.gruelbox.transactionoutbox.TransactionManager.inTransactionReturns(TransactionManager.java:93)
	at com.gruelbox.transactionoutbox.AbstractThreadLocalTransactionManager.inTransactionReturns(AbstractThreadLocalTransactionManager.java:31)
	at com.gruelbox.transactionoutbox.TransactionOutboxImpl.expireIdempotencyProtection(TransactionOutboxImpl.java:159)
	at com.gruelbox.transactionoutbox.TransactionOutboxImpl.flush(TransactionOutboxImpl.java:125)
	at com.gruelbox.transactionoutbox.acceptance.AbstractAcceptanceTest.lambda$withRunningFlusher$34(AbstractAcceptanceTest.java:631)
	at java.base/java.lang.Thread.run(Thread.java:829)
09:42:59.775 [Thread-275] DEBUG SESSION-KEY= c.g.t.TransactionOutboxImpl - Flushing stale tasks
09:42:59.775 [Thread-275] DEBUG SESSION-KEY= c.g.t.DriverConnectionProvider - Opening connection to jdbc:oracle:thin:@localhost:49214/xepdb1
09:43:00.303 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Got connection oracle.jdbc.driver.T4CConnection@6471fb01
09:43:00.303 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Setting auto-commit false
09:43:00.303 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Processing work
09:43:00.304 [Thread-275] DEBUG SESSION-KEY= c.g.t.DefaultPersistor - Found 0 results
09:43:00.304 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Committing transaction
09:43:00.305 [Thread-275] DEBUG SESSION-KEY= c.g.t.TransactionOutboxImpl - Got batch of 0
09:43:00.305 [Thread-275] DEBUG SESSION-KEY= c.g.t.TransactionOutboxImpl - Submitted batch
09:43:00.305 [Thread-275] DEBUG SESSION-KEY= c.g.t.DriverConnectionProvider - Opening connection to jdbc:oracle:thin:@localhost:49214/xepdb1
09:43:00.344 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Got connection oracle.jdbc.driver.T4CConnection@5d403d2a
09:43:00.344 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Setting auto-commit false
09:43:00.344 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Processing work
09:43:00.345 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Committing transaction
09:43:00.346 [Thread-275] DEBUG SESSION-KEY= c.g.t.TransactionOutboxImpl - No records found to delete as of 2022-10-10T07:42:59.775490Z
09:43:00.596 [Thread-275] DEBUG SESSION-KEY= c.g.t.TransactionOutboxImpl - Flushing stale tasks
09:43:00.596 [Thread-275] DEBUG SESSION-KEY= c.g.t.DriverConnectionProvider - Opening connection to jdbc:oracle:thin:@localhost:49214/xepdb1
09:43:00.696 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Got connection oracle.jdbc.driver.T4CConnection@2d4afaf8
09:43:00.697 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Setting auto-commit false
09:43:00.697 [Thread-275] DEBUG SESSION-KEY= c.g.t.SimpleTransactionManager - Processing work
09:43:00.699 [Thread-275] DEBUG SESSION-KEY= c.g.t.DefaultPersistor - Found 0 results
`

**Comment by RomainWilbert** [comment]
Seems that -Doracle.jdbc.javaNetNio=false argument helps with the execution. Can't exactly figure why.

**Comment by RomainWilbert** [comment]
Build is failing because of missing javadoc on lombok generated code :(

**Comment by skastenholz** [comment]
@badgerwithagun Any chance this nicely done PR will get an approval by this awesome project once failing checks are resolved? Thanks.

**Comment by badgerwithagun** [comment]
Absolutely @skastenholz!

If someone can fix the build I'll be happy to progress. I'll need to review it properly obviously

**Comment by skastenholz** [comment]
Hey @RomainWilbert and @badgerwithagun, I provided the following PR https://github.com/RomainWilbert/transaction-outbox/pull/4 to avoid the current build error. I assume it works this way. Otherwise please provide some guidance. Thanks.

**Comment by skastenholz** [comment]
@badgerwithagun As discussed the checks are fixed now. Please let us know if anything (else) prevents the merging of this PR. Thank you!

**Review by badgerwithagun — APPROVED** [review]

**Comment by badgerwithagun** [comment]
Great stuff, thanks both!

Merging.

**Comment by skastenholz** [comment]
Thanks a lot for merging! I am wondering how and when it will be available after releasing 5.2.337 on Maven Central (https://mvnrepository.com/artifact/com.gruelbox/transactionoutbox-core) since https://github.com/gruelbox/transaction-outbox/actions/runs/4383418970 failed.

**Comment by kzkvv** [comment]
Hi, @RomainWilbert I found that you have rewritten my previous fix for postgres, now the previous bug [I fixed in this PR](https://github.com/gruelbox/transaction-outbox/pull/367) appears again.
Could you explain please, was it a mistake while merging or the planned change? 

image

**Pull request merged**
