### PR TITLE
Add the ability to override the fetch current version query.

### PR DESCRIPTION
**Pull request by wynan**
Hopefully the last PR before I can start adding the SQL Server code. Need this to support the following fetch query:

SELECT version FROM TXNO_VERSION WITH (UPDLOCK, HOLDLOCK, ROWLOCK)"

Let me know if the preference is for small focused PRs or larger PRs.

### CODE REVIEW

**Comment by wynan** [comment]
I've been trying to reproduce the test failures locally but I'm wondering if this is an existing failure that was inherited from master?

**Comment by badgerwithagun** [comment]
Sorry for the late reply @wynan . Small PRs is indeed best 🎖️ 

I'll re-run the tests a few times so we can see if it's consistent or not.

**Comment by badgerwithagun** [comment]
Hm, a bunch of other PRs are failing similarly. There appears to be a flake. Taking a look now.

**Comment by badgerwithagun** [comment]
@wynan - tests are green now. Is this ready for review?

**Comment by wynan** [comment]
Yeah, ready for review. Let me know if you have any concerns.

**Comment by wynan** [comment]
And appreciate you fixing the tests.

**Review by badgerwithagun — APPROVED** [review]

**Comment by badgerwithagun** [comment]
👍🏻  thanks! Approved.

**Pull request merged**
